### ISSUE TITLE
Some items can't be previewed even if there are no notes

### ISSUE THREAD

**Issue by shiyuzhang98** [404neko/ZoteroQuickLookReload#1]
But previewing PDFs directly works well.

**Comment by 404neko** [comment]
Please provide the type of the items which can't be previewed

**Comment by shiyuzhang98** [comment]
https://user-images.githubusercontent.com/74309824/160337660-26744cd3-5224-45e8-9cd9-7906cb0fd767.mov

I'm not sure whether I describe the question clearly.

**Comment by 404neko** [comment]
Please follow the steps in the chapter<Log files> (the bottom of README.md),  then send the log file.

**Comment by shiyuzhang98** [comment]
(3)(+0009090): ^^^ event.key:

(3)(+0000002):

(3)(+0000001): ^^^ isToggled:

(3)(+0000000): ===>true<=== (boolean)

(3)(+0000001): ZoteroQuickLook: opening viewer

(3)(+0000001): #### root_title: Alpha-fetoprotein and ultrasonography screening for hepatocellular carcinoma

(3)(+0000013): childID: 0 current_item: Daniele et al_2004_Alpha-fetoprotein and ultrasonography screening for hepatocellular carcinoma.pdf current_distance: -977 best_distance: -977

(3)(+0000020): itemTree.render(). Displaying Item Tree

(3)(+0002248): ^^^ event.key:

(3)(+0000002):

(3)(+0000000): ^^^ isToggled:

(3)(+0000000): ===>true<=== (boolean)

(3)(+0000000): ZoteroQuickLook: opening viewer

(3)(+0000001): #### root_title:

(3)(+0000000): args:

(3)(+0000001): [ "0": "/Users/zhangshiyu/Applications/Zotero/tmp/ZoteroQuickLook/zoteroquicklook.pl" ]

(3)(+0000000): ZoteroQuickLook: thinks that no files are selected

(3)(+0000025): itemTree.render(). Displaying Item Tree

(3)(+0000013): Viewing item in pane 0

(3)(+0000000): Refreshing item box

(3)(+0000702): ^^^ event.key:

(3)(+0000002): Meta

(3)(+0000001): ^^^ isToggled:

(3)(+0000001): ===>false<=== (boolean)
---
The item type is journal article. I'm afraid I haven't send the right log file here. And I can provide the PDF for you to test if needed.

**Comment by 404neko** [comment]
The bug has been located and will be repaired in the next version

**Comment by 404neko** [comment]
The bug has been located and will be fixed in the next version

**Comment by shiyuzhang98** [comment]
Thanks. Additionally, PDFs couldn't be previewed in the setting of items of journal article containing manually-added notes.

**Comment by cjlCMU** [comment]
![image](https://user-images.githubusercontent.com/102497540/162369394-0b7e4c10-fc36-4c89-85b8-5a967e9b41f9.png)
When there are annotations extracted from pdf by the "Add Note from Anotations" function of Zotero, pdf cannot be previewed.
