### ISSUE TITLE
No preview is diplayed, and wrong version is reported

### ISSUE THREAD

**Issue by xxyxxyxyx1** [404neko/ZoteroQuickLookReload#13]
I have installed the current release, v1.4.8, by drag-and-drop into the Zotero add-on window. It appears to install fine, although it shows the version is v1.4.6 and there are no updates available. 

After restarting Zotero and selecting a reference, I do not see any preview when using [space]. Instead, the item appears non-highlighted and the details pane goes blank except "1416 items in this view". Typing [space] again returns to the original state. 

I tried with both the `.zoteroplugin` and the `.xpi` files, and the behavior was the same.

**Comment by 404neko** [comment]
Try to tap [SPACE] for multiple times, Zotero's behavior is different after 6.0, wo still thinking about how to slove this issue.

**Comment by xxyxxyxyx1** [comment]
Typing [space] repeatedly does not cause a preview to appear. It only toggles repeatedly between the initial state with the item selected, and the non-highlighted state without the details pane.

**Comment by 404neko** [comment]
Please follow this [https://github.com/404neko/ZoteroQuickLookReload#log-files](https://github.com/404neko/ZoteroQuickLookReload#log-files) then copy the content of log window then submit it here

**Comment by xxyxxyxyx1** [comment]
Here it is:
<old link>
Edit: I made a mistake, here is a new link:
https://gist.github.com/xxyxxyxyx1/af546fd3741f7481613ccb378e48049b

**Comment by YJ-He** [comment]
I got the same issue as @xxyxxyxyx1, no solution to date.

**Comment by 404neko** [comment]
> I got the same issue as @xxyxxyxyx1, no solution to date.

Colud you please submit informations about this issue follow this link? :

[https://github.com/404neko/ZoteroQuickLookReload#getting-support](https://github.com/404neko/ZoteroQuickLookReload#getting-support)

**Comment by YJ-He** [comment]
> > I got the same issue as @xxyxxyxyx1, no solution to date.
> 
> Colud you please submit informations about this issue follow this link? :
> 
> https://github.com/404neko/ZoteroQuickLookReload#getting-support

Here is the detail link https://gist.github.com/YJ-He/0b693f850aa446fdfc331d75d9e14423. 
It appears an error as below:
[JavaScript Error: "TypeError: (new Date(...)).toString(...).match(...) is null" {file: "chrome://zoteroquicklook/content/zoteroquicklook.js line 1 > eval" line: 1}]

**Comment by xxyxxyxyx1** [comment]
After upgrading to zotero 6.0.9 today, this extension now works correctly.

**Comment by YJ-He** [comment]
> After upgrading to zotero 6.0.9 today, this extension now works correctly.

Sadly, I cannot use it still, even zotero 6.0.9 is upgraded. I'm thinking about whether another plugin is conflicted with Quicklook?

**Comment by 404neko** [comment]
@YJ-He 
Didn't you updated to the latest version?

**Comment by YJ-He** [comment]
@404neko Yes, I think so, zotero is 6.0.9, and zeteroquicklook is the latest version as well. Although version number (1.4.6) of zeteroquicklook is not fit its named version (1.4.8), I did install the latest released plugin from https://github.com/404neko/ZoteroQuickLookReload/releases/tag/1.4.8.
![image](https://user-images.githubusercontent.com/95644882/176185206-ee109a4d-8005-429b-a71c-8793e2cef43b.png)
