### ISSUE TITLE
Why is the source obfuscated?

### ISSUE THREAD

**Issue by beaugunderson** [404neko/ZoteroQuickLookReload#15]
e.g.:

<img width="1713" alt="image" src="https://user-images.githubusercontent.com/61791/173442957-4b02e836-1fc5-4f96-9ac4-cbd876bf26ce.png">

**Comment by 404neko** [comment]
Some one once sold this plugin on taobao.com

**Comment by 404neko** [comment]
And taobao.com refus to take down this plugin

**Comment by beaugunderson** [comment]
that doesn't explain why the source code is obfuscated...
