### ISSUE TITLE
空格预览条目时会打开两次PDF

### ISSUE THREAD

**Issue by ghost** [404neko/ZoteroQuickLookReload#3]
如果使用 SumatraPDF 作为 PDF 阅读器，当在条目上按空格键时，会打开两次 PDF。
如果将条目展开，在选中PDF后按空格键就可以只打开一次 PDF 了。

**Comment by 404neko** [comment]
Translate by DeepL:

SumatraPDF used as a PDF reader will open the PDF twice when the space bar is pressed on the entry.
If the entry is expanded, pressing the space bar after selecting the PDF will open the PDF only once.

**Comment by ghost** [comment]
> Translate by DeepL:
> 
> SumatraPDF used as a PDF reader will open the PDF twice when the space bar is pressed on the entry. If the entry is expanded, pressing the space bar after selecting the PDF will open the PDF only once.

👍
