### ISSUE TITLE
The latest 1.4.4 version of QuickLook does not work

### ISSUE THREAD

**Issue by mingjiemile** [404neko/ZoteroQuickLookReload#5]
The specific situation is that when you open Zotero or select the PDF and press the space bar, a prompt box for "The version has expired, please download the new version." will pop up.
Like this:
case of Windows
![Windows edition](https://user-images.githubusercontent.com/48385968/162609177-31ca55ca-b789-46f9-84ed-b09a305575c5.png)
case of Mac
<img width="464" alt="Mac edition" src="https://user-images.githubusercontent.com/48385968/162609192-7932f9da-ad27-4894-9be6-266d6e26d6d9.png">

**Comment by 404neko** [comment]
Sorry, please update to 1.4.5

**Comment by mingjiemile** [comment]
Thank you very much！
