### ISSUE TITLE
One PDF will be opened twice

### ISSUE THREAD

**Issue by ghost** [404neko/ZoteroQuickLookReload#7]
Translated by **[Google Translate](/translate.google.cn)**

If you use SumatraPDF as your PDF reader, when you press the space bar on an entry, the PDF is opened twice.
If you expand the entry, you can open the PDF only once by pressing the space bar after selecting the PDF.

**Comment by 404neko** [comment]
It is a known issue, we still thinking about how to fix this.
Will be fix at 1.4.7

**Comment by ghost** [comment]
> It is a known issue, we still thinking about how to fix this. Will be fix at 1.4.7

Looking forward to the new version 👍
