### ISSUE TITLE
Clarify "expired" message

### ISSUE THREAD

**Issue by dstillman** [404neko/ZoteroQuickLookReload#8]
We've gotten multiple reports in the Zotero Forums from users confused about this message. I'm not sure why a version is being expired rather than just pushing an update and letting it auto-update like other plugins, but if you're going to continue showing this message, can you clarify it to make it clear it's about this plugin?

https://forums.zotero.org/discussion/96286/javascript-application-the-version-has-expired-please-download-the-new-version
https://forums.zotero.org/discussion/96396/javascript-application-the-version-has-expired-please-download-the-new-version

**Comment by 404neko** [comment]
Yes, it is from ZoteroQuickLookReload.

At that time, ZoteroQuickLookReload was under frequent development
In order to ensure that users will not use plug-ins with incomplete functions, a time limit is set
This restriction has been removed in version 1.4.8

Thanks for reporting

**Comment by dstillman** [comment]
OK, thanks.
