### ISSUE TITLE
New Add-on Filename Extension .xpi for Zotero 6.x

### ISSUE THREAD

**Issue by Regulust** [404neko/ZoteroQuickLookReload#9]
Hi, 
Thanks for creat this new version of ZoteroQuickLookReload add-on. It works well with Zotero 6.x.
Zotero 6.x use .xpi (.zip) extension name for add-ons, could you create a .xpi (.zip) file in Releases for easily installing on Zotero 6.x.
Thanks again.

**Comment by 404neko** [comment]
Yep~
I will do it
